export * from './home';
export * from './profile-preference';

export type Category = {
  ID: string;
  Name: string;
  ParentID?: string;
  Parent?: Category;
};

export type SizeUnit = {
  ID: string;
  Name: string;
};

export type ItemDefinition = {
  ID: string;
  Name: string;
  Description: string;
  CategoryID?: string;
  Category?: Category;
  SizeUnitID?: string;
  SizeUnit?: SizeUnit;
  IsExpirable: boolean;
  ImageURL: string;
  barcode?: string | null;
  LowStockThreshold?: number;
};

export type ItemDefinitionRequest = {
  name: string;
  description?: string;
  category_id?: string;
  size_unit_id: string;
  is_expirable: boolean;
  image_url?: string;
  barcode?: string | null;
  low_stock_threshold?: number | null;
};

export type InventoryItem = {
  ID: string;
  HomeID: string;
  ItemDefinitionID: string;
  Quantity: number;
  ExpirationDate?: string;
  ItemDefinition: ItemDefinition;
};

export type CreateInventoryItemRequest = {
  item_definition_id: string;
  quantity: number;
  expiry_date?: string | null;
};

export type UpdateInventoryItemRequest = {
  quantity: number;
  expiry_date?: string | null;
};

export type AlmostFinishedItemResponse = {
  item_definition: ItemDefinition;
  total_quantity: number;
  reason: string;
  estimated_days_left: number;
};

export type ShoppingListItem = {
  ID: string;
  HomeID: string;
  ItemDefinitionID?: string;
  ItemDefinition?: ItemDefinition;
  Name: string;
  Quantity: number;
  IsAutoGenerated: boolean;
  IsBought: boolean;
  CreatedAt: string;
  UpdatedAt: string;
};

export type ShoppingListItemRequest = {
  item_definition_id?: string;
  name?: string;
  quantity: number;
};

export type UpdateShoppingListItemRequest = {
  is_bought?: boolean;
  quantity: number;
};

export type ProductLookupResponse = {
  barcode: string;
  name: string;
  category?: string;
  image_url?: string;
};

export type BarcodeScanRequest = {
  barcode: string;
  change: number;
};
